language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sohammodhe/docker-react -f Dockerfile.dev .

script:
  - docker run sohammodhe/docker-react npm run test -- --coverage